const ActionTypes = {
    LOG_IN:"LOG_IN",
    SIGN_UP:"SIGN_UP",
    ADMIN_DATA:"ADMIN_DATA",
    STUDENT_ADMIN_DATA:"STUDENT_ADMIN_DATA",
    COMPANY_ADMIN_DATA:"COMPANY_ADMIN_DATA",
    COMPANY_DATA:"COMPANY_DATA",
    COMPANY_DELETE:"COMPANY_DELETE",
    STUDENT_DELETE:"STUDENT_DELETE",
    STUDENT_DATA:"STUDENT_DATA",
    SING_OUT:"SING_OUT"

    
}

export default ActionTypes